# Generated by Django 3.2.9 on 2023-03-11 16:11

import agro.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50, verbose_name='Nomi (uz)')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Nomi (ru)')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
            bases=(agro.mixins.TranslateMixin, models.Model),
        ),
    ]
