# Generated by Django 3.2.9 on 2023-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=None, max_length=50, verbose_name='Nomi (en)'),
            preserve_default=False,
        ),
    ]
