# Generated by Django 3.2.9 on 2023-03-13 16:28

import agro.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230311_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi_uz', models.CharField(max_length=50, verbose_name='Nomi (uz)')),
                ('nomi_en', models.CharField(max_length=50, verbose_name='Nomi (en)')),
                ('image', models.FileField(upload_to='media')),
            ],
            options={
                'verbose_name': 'Tovar nomi',
            },
            bases=(agro.mixins.TranslateMixin, models.Model),
        ),
    ]
