# Generated by Django 3.2.9 on 2023-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230313_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(default=None, upload_to='media'),
            preserve_default=False,
        ),
    ]
