# Generated by Django 3.2.9 on 2023-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_category_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Content (en)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Content (uz)'),
        ),
    ]
