# Generated by Django 3.2.9 on 2023-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20231209_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content (en)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content (uz)'),
        ),
    ]
