# Generated by Django 3.2.9 on 2023-12-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20231209_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
                ('subject_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject (uz)')),
                ('subject_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject (en)')),
                ('content_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Content (uz)')),
                ('content_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Content (en)')),
            ],
            options={
                'verbose_name': 'Servis nomi',
                'verbose_name_plural': 'Servis nomlari',
            },
        ),
    ]
