# Generated by Django 3.2.9 on 2023-12-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content_en',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Content (en)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_uz',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Content (uz)'),
        ),
    ]
